code/JewelryShop/JewelryShop/Areas/Administrator/Controllers/DanhMucController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JewelryShop.Model;
using JewelryShop.Repository;
using PagedList;

namespace JewelryShop.Areas.Administrator.Controllers
{
    public class DanhMucController : Controller
    {
        DanhMucRepository dmRepo = null;

        public DanhMucController()
        {
            dmRepo = new DanhMucRepository();
        }

        // GET: Administrator/DanhMuc
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetPaging(int? page)
        {
            int pageSize = 10; // Số sản phẩm của 1 trang
            int pageNum = (page ?? 1); // If(page==null)->set page==1

            return PartialView("_GetPaging", dmRepo.GetAll().ToPagedList(pageNum, pageSize));
        }

        public ActionResult Create()
        {
            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DanhMucID,TenDanhMuc,TrangThai")] DanhMuc danhMuc)
        {
            if (ModelState.IsValid)
            {
                dmRepo.Create(danhMuc);
                return RedirectToAction("Index");
            }

            return View(danhMuc);
        }
        
        public ActionResult Edit(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DanhMuc danhMuc = dmRepo.GetByID(id);
            if (danhMuc == null)
            {
                return HttpNotFound();
            }
            return View(danhMuc);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DanhMucID,TenDanhMuc,TrangThai")] DanhMuc danhMuc)
        {
            if (ModelState.IsValid)
            {
                dmRepo.Update(danhMuc);
                return RedirectToAction("Index");
            }
            return View(danhMuc);
        }
        
        public ActionResult Delete(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DanhMuc danhMuc = dmRepo.GetByID(id);
            if (danhMuc == null)
            {
                return HttpNotFound();
            }
            return View(danhMuc);
        }
        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            dmRepo.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

code/JewelryShop/JewelryShop/Areas/Administrator/Views/DanhMuc/Create.cshtml
@model JewelryShop.Model.DanhMuc

@{
    ViewBag.Title = "Create";
}

<h2>Tạo danh mục mới</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TenDanhMuc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenDanhMuc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenDanhMuc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TrangThai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TrangThai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TrangThai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm mới" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay lại", "Index")
</div>

code/JewelryShop/JewelryShop/Areas/Administrator/Views/DanhMuc/Delete.cshtml
@model JewelryShop.Model.DanhMuc

@{
    ViewBag.Title = "Delete";
}

<h2>Xoá danh mục</h2>

<h3>Bạn có chắc chắn muốn xoá ?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenDanhMuc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenDanhMuc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TrangThai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TrangThai)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xoá" class="btn btn-danger" />
            <br />
            @Html.ActionLink("Quay lại", "Index")
        </div>
    }
</div>

code/JewelryShop/JewelryShop/Areas/Administrator/Views/DanhMuc/Details.cshtml
@model JewelryShop.Model.DanhMuc

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>DanhMuc</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenDanhMuc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenDanhMuc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TrangThai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TrangThai)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Sửa", "Edit", new { id = Model.DanhMucID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

code/JewelryShop/JewelryShop/Areas/Administrator/Views/DanhMuc/Edit.cshtml
@model JewelryShop.Model.DanhMuc

@{
    ViewBag.Title = "Edit";
}

<h2>Cập nhật danh mục</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.DanhMucID)

        <div class="form-group">
            @Html.LabelFor(model => model.TenDanhMuc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenDanhMuc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenDanhMuc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TrangThai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TrangThai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TrangThai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-info" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay lại", "Index")
</div>

code/JewelryShop/JewelryShop/Areas/Administrator/Views/DanhMuc/Index.cshtml
@{
    Layout = null;
}

<div id="DanhMuc_Area">
    @{ Html.RenderAction("GetPaging", "DanhMuc", new { page = 1 });}
</div>

code/JewelryShop/JewelryShop/Areas/Administrator/Views/DanhMuc/_GetPaging.cshtml
@using PagedList.Mvc
@model PagedList.IPagedList<JewelryShop.Model.DanhMuc>
@{
    Layout = "~/Areas/Administrator/Views/Shared/_Layout.cshtml";
}

<h2>Danh sách danh mục</h2>

<p>
    @Html.ActionLink("Thêm mới", "Create")
</p>
<table class="table">
    <tr>
        <th>Mã danh mục</th>
        <th>Tên danh mục</th>
        <th>Trạng thái</th>
        <th>Chức năng</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@item.DanhMucID</td>
            <td>@item.TenDanhMuc</td>
            <td>@item.TrangThai</td>
            <td>
                @Html.ActionLink("Sửa", "Edit", new { id = item.DanhMucID }) |
                @Html.ActionLink("Xoá", "Delete", new { id = item.DanhMucID })
            </td>
        </tr>
    }

</table>

<br />
@Html.PagedListPager(Model, page => Url.Action("GetPaging", new { page }),
    PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions()
    { HttpMethod = "GET", UpdateTargetId = "DanhMuc_Area" }))