code/JewelryShop/JewelryShop/Areas/Administrator/Controllers/HoaDonController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JewelryShop.Model;
using JewelryShop.Repository;
using PagedList;

namespace JewelryShop.Areas.Administrator.Controllers
{
    public class HoaDonController : Controller
    {
        HoaDonRepository hdRepo = null;

        public HoaDonController()
        {
            hdRepo = new HoaDonRepository();
        }

        // GET: Administrator/HoaDon
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetPaging(int? page)
        {
            int pageSize = 10; // Số sản phẩm của 1 trang
            int pageNum = (page ?? 1); // If(page==null)->set page==1

            return PartialView("_GetPaging", hdRepo.GetAll().ToPagedList(pageNum, pageSize));
        }

        public ActionResult Details(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HoaDon hoaDon = hdRepo.GetByID(id);
            if (hoaDon == null)
            {
                return HttpNotFound();
            }
            return View(hoaDon);
        }
        
        public ActionResult Edit(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HoaDon hoaDon = hdRepo.GetByID(id);
            if (hoaDon == null)
            {
                return HttpNotFound();
            }
            return View(hoaDon);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "HoaDonID,KhachHangID,NgayDatHang,NgayGiaoHang,NguoiNhan,DiaChiNhan,DienThoai,TongTien,TrangThai")] HoaDon hoaDon)
        {
            if (ModelState.IsValid)
            {
                hdRepo.Update(hoaDon);
                return RedirectToAction("Index");
            }
            return View(hoaDon);
        }
    }
}

code/JewelryShop/JewelryShop/Areas/Administrator/Views/HoaDon/Details.cshtml
@model JewelryShop.Model.HoaDon

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>HoaDon</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.KhachHangID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KhachHangID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgayDatHang)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayDatHang)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgayGiaoHang)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayGiaoHang)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NguoiNhan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NguoiNhan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DiaChiNhan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiaChiNhan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DienThoai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DienThoai)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TongTien)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TongTien)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TrangThai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TrangThai)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.HoaDonID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

code/JewelryShop/JewelryShop/Areas/Administrator/Views/HoaDon/Edit.cshtml
@model JewelryShop.Model.HoaDon

@{
    ViewBag.Title = "Edit";
}

<h2>Cập nhật đơn hàng</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.HoaDonID)

        <div class="form-group">
            @Html.LabelFor(model => model.KhachHangID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.KhachHangID, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                @Html.ValidationMessageFor(model => model.KhachHangID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgayDatHang, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayDatHang, new { htmlAttributes = new { @class = "form-control", type= "date", @disabled = "disabled" } })
                @Html.ValidationMessageFor(model => model.NgayDatHang, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgayGiaoHang, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayGiaoHang, new { htmlAttributes = new { @class = "form-control", type= "date" } })
                @Html.ValidationMessageFor(model => model.NgayGiaoHang, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NguoiNhan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NguoiNhan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NguoiNhan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DiaChiNhan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiaChiNhan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiaChiNhan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DienThoai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DienThoai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DienThoai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TongTien, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TongTien, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TongTien, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TrangThai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TrangThai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TrangThai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay lại", "Index")
</div>

code/JewelryShop/JewelryShop/Areas/Administrator/Views/HoaDon/Index.cshtml
@{
    Layout = null;
}

<div id="SanPham_Area">
    @{ Html.RenderAction("GetPaging", "HoaDon", new { page = 1 });}
</div>

code/JewelryShop/JewelryShop/Areas/Administrator/Views/HoaDon/_GetPaging.cshtml
@using PagedList.Mvc
@model PagedList.IPagedList<JewelryShop.Model.HoaDon>
@{
    Layout = "~/Areas/Administrator/Views/Shared/_Layout.cshtml";
}

<h2>Danh sách hoá đơn</h2>

<p>
</p>
<table class="table">
    <tr>
        <th>Mã hoá đơn</th>
        <th>Mã khách hàng</th>
        <th>Ngày đặt hàng</th>
        <th>Ngày giao hàng</th>
        <th>Người nhận</th>
        <th>Địa chỉ nhận</th>
        <th>Điện thoại</th>
        <th>Tổng tiền</th>
        <th>Trạng thái</th>
        <th>Chức năng</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@item.HoaDonID</td>
            <td>@item.KhachHangID</td>
            <td>@item.NgayDatHang</td>
            <td>@item.NgayGiaoHang</td>
            <td>@item.NguoiNhan</td>
            <td>@item.DiaChiNhan</td>
            <td>@item.DienThoai</td>
            <td>@item.TongTien</td>
            <td>@item.TrangThai</td>
            <td>
                @Html.ActionLink("Sửa", "Edit", new { id = item.HoaDonID })
            </td>
        </tr>
    }

</table>

<br />
@Html.PagedListPager(Model, page => Url.Action("GetPaging", new { page }),
    PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions()
    { HttpMethod = "GET", UpdateTargetId = "HoaDon_Area" }))